#!/usr/bin/python3
import time
import os
import subprocess
from os import system
from subprocess import call

def Banner():
  print("▄▄▄█████▓ ▒█████  ▒██   ██▒ ██▓ ▄████▄    ██████ ▓█████  ▄████▄  ")
  print("▓  ██▒ ▓▒▒██▒  ██▒▒▒ █ █ ▒░▓██▒▒██▀ ▀█  ▒██    ▒ ▓█   ▀ ▒██▀ ▀█  ")
  print("▒ ▓██░ ▒░▒██░  ██▒░░  █   ░▒██▒▒▓█    ▄ ░ ▓██▄   ▒███   ▒▓█    ▄ ")
  print("░ ▓██▓ ░ ▒██   ██░ ░ █ █ ▒ ░██░▒▓▓▄ ▄██▒  ▒   ██▒▒▓█  ▄ ▒▓▓▄ ▄██▒")
  print("  ▒██▒ ░ ░ ████▓▒░▒██▒ ▒██▒░██░▒ ▓███▀ ░▒██████▒▒░▒████▒▒ ▓███▀ ░")
  print("  ▒ ░░   ░ ▒░▒░▒░ ▒▒ ░ ░▓ ░░▓  ░ ░▒ ▒  ░▒ ▒▓▒ ▒ ░░░ ▒░ ░░ ░▒ ▒  ░")
  print("    ░      ░ ▒ ▒░ ░░   ░▒ ░ ▒ ░  ░  ▒   ░ ░▒  ░ ░ ░ ░  ░  ░  ▒   ")
  print("  ░      ░ ░ ░ ▒   ░    ░   ▒ ░░        ░  ░  ░     ░   ░        ")
  print("             ░ ░   ░    ░   ░  ░ ░            ░     ░  ░░ ░      ")
  print("                               ░                        ░        ")
  print("  ██████ ▓█████▄▄▄█████▓ █    ██  ██▓███                         ")
  print("▒██    ▒ ▓█   ▀▓  ██▒ ▓▒ ██  ▓██▒▓██░  ██▒                       ")
  print("░ ▓██▄   ▒███  ▒ ▓██░ ▒░▓██  ▒██░▓██░ ██▓▒                       ")
  print("  ▒   ██▒▒▓█  ▄░ ▓██▓ ░ ▓▓█  ░██░▒██▄█▓▒ ▒                       ")
  print("▒██████▒▒░▒████▒ ▒██▒ ░ ▒▒█████▓ ▒██▒ ░  ░                       ")
  print("▒ ▒▓▒ ▒ ░░░ ▒░ ░ ▒ ░░   ░▒▓▒ ▒ ▒ ▒▓▒░ ░  ░                       ")
  print("░ ░▒  ░ ░ ░ ░  ░   ░    ░░▒░ ░ ░ ░▒ ░                            ")
  print("░  ░  ░     ░    ░       ░░░ ░ ░ ░░                              ")
  print("      ░     ░  ░           ░                                     ")
  print("                                                                 ")

def Animations():
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]-[Install]-[*]: Avvio installazione del ToxicSec.")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]\[Install]/[*]: Avvio installazione del ToxicSec..")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]|[Install]|[*]: Avvio installazione del ToxicSec...")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]/[Install]\[*]: Avvio installazione del ToxicSec.")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]-[Install]-[*]: Avvio installazione del ToxicSec..")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]\[Install]/[*]: Avvio installazione del ToxicSec...")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]|[Install]|[*]: Avvio installazione del ToxicSec.")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]/[Install]\[*]: Avvio installazione del ToxicSec..")
  print("-------------------------------------------------------")
  time.sleep(0.5)
  subprocess.run(["clear"])
  Banner()
  print()
  print("-------------------------------------------------------")
  print("[*]-[Install]-[*]: Avvio installazione del ToxicSec...")
  print("-------------------------------------------------------")
  time.sleep(0.5)

def PyPhisher():
  call(["sh", "-c", "pip3 install pyphisher"])
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di PyPhisher.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di PyPhisher..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di PyPhisher...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di PyPhisher.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di PyPhisher..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di PyPhisher..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di PyPhisher...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di PyPhisher.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di PyPhisher..")
  time.sleep(0.5)

def Venom():
  call(["sh", "-c", "sudo git clone https://github.com/r00t-3xp10it/venom.git && cd Venom && chmod +x * && cd aux && sudo ./setup.sh"])
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di Venom.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di Venom..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di Venom...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di Venom.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di Venom..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di Venom..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di Venom...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di Venom.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di Venom..")
  time.sleep(0.5)

def MHDDoS():
  call(["sh", "-c", "git clone https://github.com/MatrixTM/MHDDoS.git && cd MH* && pip3 install -r requirements.txt"])
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di MHDDoS.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di MHDDoS..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di MHDDoS...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di MHDDoS.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di MHDDoS..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di MHDDoS...")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di MHDDoS.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]/[Install]\[*]: Installazione di MHDDoS..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di MHDDoS...")
  time.sleep(0.5)
  
def msfinstall():
  call(["sh", "-c", "python3 msfinstall.py"])
  subprocess.run(["clear"])
  print("[*]-[Install]-[*]: Installazione di Metasploit.")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]\[Install]/[*]: Installazione di Metasploit..")
  time.sleep(0.5)
  subprocess.run(["clear"])
  print("[*]|[Install]|[*]: Installazione di Metasploit...")


Animations()

PyPhisher()
time.sleep(5)
Venom()
time.sleep(5)
MHDDoS()
time.sleep(5)
msfinstall()
time.sleep(10)
print("")
print("-----------------------------------------------------------")
print("[*]-[Install]-[*]: Installazione comepletata con successo!")
print("-----------------------------------------------------------")
time.sleep(2)
subprocess.run(["clear"])
print("[*]-[Info]-[*]: Avvio del tool in corso...")
subprocess.run(["sh", "-c", "python3 ToxicSec.py"])
