
#!/usr/bin/python3
import time
import os
import subprocess
from os import system
from subprocess import call

def animation():
  print("\x1b[8;29;135t")
  
  
  print("█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████")
  print("█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░██░░░░░░░░█░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█")
  print("█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█░░▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█")
  print("█░░░░░░▄▀░░░░░░█░░▄▀░░░░░░▄▀░░█░░░░▄▀░░██░░▄▀░░░░█░░░░▄▀░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█")
  print("█████░░▄▀░░█████░░▄▀░░██░░▄▀░░███░░▄▀▄▀░░▄▀▄▀░░█████░░▄▀░░███░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░█████████")
  print("█████░░▄▀░░█████░░▄▀░░██░░▄▀░░███░░░░▄▀▄▀▄▀░░░░█████░░▄▀░░███░░▄▀░░█████████░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░█████████")
  print("█████░░▄▀░░█████░░▄▀░░██░░▄▀░░█████░░▄▀▄▀▄▀░░███████░░▄▀░░███░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░█████████")
  print("█████░░▄▀░░█████░░▄▀░░██░░▄▀░░███░░░░▄▀▄▀▄▀░░░░█████░░▄▀░░███░░▄▀░░█████████░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░█████████")
  print("█████░░▄▀░░█████░░▄▀░░██░░▄▀░░███░░▄▀▄▀░░▄▀▄▀░░█████░░▄▀░░███░░▄▀░░█████████████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░█████████")
  print("█████░░▄▀░░█████░░▄▀░░░░░░▄▀░░█░░░░▄▀░░██░░▄▀░░░░█░░░░▄▀░░░░█░░▄▀░░░░░░░░░░█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█")
  print("█████░░▄▀░░█████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█░░▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█")
  print("█████░░▄▀░░█████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀░░██░░▄▀▄▀░░█░░▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█")
  print("█████░░░░░░█████░░░░░░░░░░░░░░█░░░░░░░░██░░░░░░░░█░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█")
  print("█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████")

  time.sleep(3)

  subprocess.run(["clear"])

  print("\x1b[8;26;109t")

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒╟┐")
  print("                                            ║█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║████▒▒▒▒▒▒▒▒▒▒▒▒▒╟┐")
  print("                                            ║████▒▒▒▒▒▒▒▒▒▒▒▒▒╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║███████▒▒▒▒▒▒▒▒▒▒╟┐")
  print("                                            ║███████▒▒▒▒▒▒▒▒▒▒╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║███████████▒▒▒▒▒▒╟┐")
  print("                                            ║███████████▒▒▒▒▒▒╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║██████████████▒▒▒╟┐")
  print("                                            ║██████████████▒▒▒╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

  print("                                             ")
  print("                                  ᑕᗩᖇIᑕᗩᗰEᑎTO ᗪEᒪ TOOᒪ Iᑎ ᑕOᖇᔕO - ᗩTTEᑎᗪEᖇE ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                             ")
  print("                                            ╔═════════════════╗")
  print("                                            ║█████████████████╟┐")
  print("                                            ║█████████████████╟┘")
  print("                                            ╚═════════════════╝")

  time.sleep(1)

  subprocess.run(["clear"])

def menu():
  subprocess.run(["clear"])
  print("  _______                   __          _______                  _______                   __ ") 
  print(" |       | .-----. .--.--. |__| .----. |   _   | .-----. .----. |       | .-----. .-----. |  |")
  print(" |.|   | | |  _  | |_   _| |  | |  __| |   1___| |  -__| |  __| |.|   | | |  _  | |  _  | |  |")
  print(" `-|.  |-' |_____| |__.__| |__| |____| |____   | |_____| |____| `-|.  |-' |_____| |_____| |__|")
  print("   |:  |                               |:  1   |                  |:  |")                       
  print("   |::.|                               |::.. . |                  |::.|")                       
  print("   `---'                               `-------'                  `---'")

  time.sleep(1)

  print("")
  print("                                    -𝓒𝓱𝓸𝓸𝓼𝓮  𝔂𝓸𝓾𝓻  𝓞𝓹𝓽𝓲𝓸𝓷𝓼 -")
  print("")
  print("             ┏══════════════════════════════════════════════════════════════════┓")
  print("              『1』│ ᑭᕼIՏᕼIᑎᘜ")
  print("              『2』│ ᗴ᙭ᑭᒪOIT")
  print("              『3』│ ᗪᗪOՏ") 
  print("              『4』│ OՏIᑎT")
  print("              『5』│ Update Tools")
  print("             ┗══════════════════════════════════════════════════════════════════┛")

#BANNER DDOS

def bannerddos():
  print(".________________________________________________.")
  print("|             :!Attenzione!:                     |")
  print("|La Proxy List è vuota, pertanto l'attacco verrà |")
  print("|          effettuato senza Proxy.               |")
  print("|________________________________________________|")
  print("|Proxy Type 0 = Tutto in config.json             |")
  print("|                                                |")
  print("|SocksTypes: - 6 = RANDOM                        |")
  print("|            - 5 = SOCKS5                        |")
  print("|            - 4 = SOCKS4                        |")
  print("|            - 1 = HTTP                          |")
  print("|            - 0 = TUTTI                         |")
  print("|________________________________________________|")
  print("")

  time.sleep(2)

  print("________________________________________________________________")
  print("|____Layer 4_____|____Layer 7_____|_____Tools____|____Other____|")
  print("|   CONNECTION   |      BOMB      |     DSTAT    |    TOOLS    |")
  print("|      TCP       |      GET       |     CHECK    |    HELP     |")
  print("|      NTP       |     STOMP      |     CFIP     |    STOP     |")
  print("|     CLDAP      |     POST       |     PING     |_____________|")
  print("|      SYN       |     APACHE     |     TSSRV    |  3 Methods")
  print("|      ARD       |      TOR       |     INFO     |")
  print("|      DNS       |      GSB       |     DNS      |")
  print("|     ICMP       |     CFBUAM     |______________|")
  print("|     CHAR       |      PPS       |   7 Methods")
  print("|     MCBOT      |      DGB       |")
  print("|      VSE       |     COOKIE     |")
  print("|      MEM       |      AVB       |")
  print("|      UDP       |      DYN       |")
  print("|      RDP       |      BOT       |")
  print("|      TS3       |     XMLRPC     |")
  print("|      MCPE      |      EVEN      |")
  print("|     FIVEM      |     BYPASS     |")
  print("|   Minecraft    |      CFB       |")
  print("|      CPS       |     KILLER     |")
  print("|________________|      OVH       |")
  print("    19 Methods   |      SLOW      |")
  print("                 |      NULL      |")
  print("                 |      RHEX      |")
  print("                 |   DOWNLOADER   |")
  print("                 |      HEAD      |")
  print("                 |     STRESS     |")
  print("                 |________________|")
  print("                     26 Methods")
  print("ALL: 55 Methods")

  time.sleep(2)

  print("_________________________________________________________________________________________________________________________")
  print("Example Command Attack:")
  print("")
  print("L7: python3 start.py <method> <url> <socks_type> <threads> <proxylist> <rpc> <duration> <debug=optional>")
  print("L4: python3 start.py <method> <ip:port> <threads> <duration>")
  print("L4 Proxied: python3 start.py <method> <ip:port> <threads> <duration> <socks_type> <proxylist>")
  print("L4 Amplification: python3 start.py <method> <ip:port> <threads> <duration> <reflector file (only use with Amplification)>")
  print("_________________________________________________________________________________________________________________________")
  print("")
  print("")

animation()

def scelta1():
  menu()
  print("")
  choose = input("[*]-[Info]-[*] Perfavore inserisci un opzione: ")

  if choose == str(1):
      call(["sh", "-c", "pyphisher"])
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(2)
      subprocess.run(["clear"])
      scelta1()

  if choose == str(2):
      call(["sh", "-c", "cd venom && sudo ./venom.sh"])
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(2)
      subprocess.run(["clear"])
      scelta1()

  if choose == str(3):
      print("[*]-[Info]-[*]: Console DDoS avviata con successo!")
      bannerddos()
      InsDdos = input("[Toxic DDos Console] $: ")
      call(["sh", "-c", f"cd MHDDoS && {InsDdos}"])
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]/[Info]\[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]|[Info]|[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]\[Info]/[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso.")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso..")
      time.sleep(0.5)
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Riavvio del tool in corso...")
      time.sleep(2)
      subprocess.run(["clear"])
      scelta1()

  if choose == str(5):
      print("[*]-[Info]-[*]: Aggiornamento del tools in corso...")
      call(["sh", "-c", "cd .. && cp /ToxicSecTools/update.py /update.py && python3 update.py"])
      subprocess.run(["clear"])
      print("[*]-[Info]-[*]: Sovraiscrizione dei dati in corso...")
      time.sleep(0.5)

  else:
      subprocess.run(["clear"])
      time.sleep(1)
      print("[*]-[!]-[*]: --!Scelta Errata!--")
      time.sleep(1)
      scelta1()

scelta1()
